#:schema node_modules/wrangler/config-schema.json
name = "workerbot"
main = "server/index.js"
compatibility_date = "2024-09-23"
node_compat = true

[vars]

database='postgresql://neondb_owner:npg_iycjf5qhb8Me@ep-nameless-shadow-a8czemhb-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require'


[triggers]

crons = ["0 */2 * * *"]  # Every 2 hours
